# Generated by Django 4.1.3 on 2023-10-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padre',
            new_name='Representante',
        ),
    ]
